
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu May 04 17:33:23 CDT 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 3;
  public static final int POR = 4;
  public static final int FIN = 8;
  public static final int EOF = 0;
  public static final int MAS = 2;
  public static final int NUMERO = 9;
  public static final int PARI = 6;
  public static final int DIV = 5;
  public static final int error = 1;
  public static final int PARD = 7;
}

