package compilador;
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue May 30 08:09:53 CDT 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 4;
  public static final int AND = 15;
  public static final int PUNTO = 8;
  public static final int ELSE = 25;
  public static final int OR = 16;
  public static final int IGUAL = 7;
  public static final int FINLINEA = 14;
  public static final int CIERRALLAVE = 12;
  public static final int ABREPAR = 9;
  public static final int Identificador = 2;
  public static final int IF = 24;
  public static final int LOGIC = 19;
  public static final int TEXTDEC = 13;
  public static final int FLOTANTE = 20;
  public static final int CLASE = 17;
  public static final int POR = 5;
  public static final int RUTINA = 21;
  public static final int CIERRAPAR = 10;
  public static final int EOF = 0;
  public static final int DIV = 6;
  public static final int TEXTO = 22;
  public static final int ABRELLAVE = 11;
  public static final int NUMERO = 23;
  public static final int error = 1;
  public static final int ENTERO = 18;
  public static final int MAS = 3;
}

